# Pandas with python series

In [ ]:
import pandas as pd

In [2]:
lst=[1,2,3,4,5,6,7,8,9,10]

In [3]:
series = pd.Series(lst)
print(series)
print(type(series))

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
<class 'pandas.core.series.Series'>

In [2]:
import pandas as pd

In [7]:
empty = pd.Series([1,2],index=[11,12],dtype=bool,name='Numbers')
print(empty)

11    True
12    True
Name: Numbers, dtype: bool

In [5]:
a = pd.Series(['a','b','c','d'], index=[1,2,3,4],name='letters')
a

1    a
2    b
3    c
4    d
Name: letters, dtype: object

In [6]:
scalar_series= pd.Series(0.5, index=[1,2,3,4])
scalar_series

1    0.5
2    0.5
3    0.5
4    0.5
dtype: float64

# Pandas series with dictionary

In [7]:
dc_series = pd.Series({'a':1, 'b':2, 'c':3})
dc_series

a    1
b    2
c    3
dtype: int64

In [8]:
dc_series[0]

C:\Users\Kousimon\AppData\Local\Temp\ipykernel_4240\2339392027.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  dc_series[0]

np.int64(1)

In [9]:
dc_series[2]

C:\Users\Kousimon\AppData\Local\Temp\ipykernel_4240\3442048473.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  dc_series[2]

np.int64(3)

In [10]:
dc_series[0:3]

a    1
b    2
c    3
dtype: int64

In [11]:
max(dc_series)

3

In [12]:
dc2_series = pd.Series({'a':[1,2,3], 'b':[4,5,6], 'c':[7,8,9]}) 
dc2_series

a    [1, 2, 3]
b    [4, 5, 6]
c    [7, 8, 9]
dtype: object

In [13]:
print(dc2_series['a'])

[1, 2, 3]

# Pandas dataframe

In [14]:
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [15]:
lst = [[1,2,3,4,5],[6,7,8,9,10]]
df=pd.DataFrame(lst)
df

   0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10

In [16]:
a=[{'a':1,'b':2,'c':3,'d':4},{'a':5,'b':6,'c':7,'d':8}]
df=pd.DataFrame(a)
df

   a  b  c  d
0  1  2  3  4
1  5  6  7  8

In [17]:
b={'Rol_no':pd.Series([1,2,3,4,5]),
   'Name':pd.Series(['a','b','c','d','e']),
   'Age':pd.Series([20,21,22,23,24])}
df=pd.DataFrame(b)
df

   Rol_no Name  Age
0       1    a   20
1       2    b   21
2       3    c   22
3       4    d   23
4       5    e   24

In [8]:
df=pd.read_csv('C:/Users/Kousimon/OneDrive/Desktop/Data Scientist/Numpy/churn.csv')
df.head()

,Unnamed: 0,customerID,tenure,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,gender,SeniorCitizen,...,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Churn
0,1,8260-NGFNY,One,Month-to-month,No,Mailed check,25.2,25.20,Female,0.0,...,No,No phone service,DSL,No,No,No,No,No,No,Yes
1,2,2359-QWQUL,39,One year,Yes,Credit card (automatic),104.7,4134.85,Female,0.0,...,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Yes
2,3,6598/RFFVI,2,One year,No,Credit card (automatic),19.3,28.30,Male,0.0,...,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Yes
3,4,IXSTS-8780,6,Month-to-month,Yes,Electronic check,90.1,521.30,Female,0.0,...,Yes,Yes,Fiber optic,No,Yes,No,No,Yes,No,Yes
4,5,2674/MIAHT,Four,Month-to-month,Yes,Mailed check,80.3,324.20,Female,0.0,...,Yes,Yes,Fiber optic,No,Yes,No,No,No,No,No

In [52]:
df.nunique()

Unnamed: 0          227
customerID          220
tenure               67
Contract              3
PaperlessBilling      2
PaymentMethod         4
MonthlyCharges      200
TotalCharges        219
gender                2
SeniorCitizen         2
Partner               2
Dependents            3
PhoneService          2
MultipleLines         3
InternetService       3
OnlineSecurity        3
OnlineBackup          3
DeviceProtection      3
TechSupport           3
StreamingTV           3
StreamingMovies       3
Churn                 2
dtype: int64

Head(), tail()

In [19]:
df.shape

(257, 22)

In [20]:
df.columns

Index(['Unnamed: 0', 'customerID', 'tenure', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'gender',
       'SeniorCitizen', 'Partner', 'Dependents', 'PhoneService',
       'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'Churn'],
      dtype='object')

In [21]:
df.tail()

,Unnamed: 0,customerID,tenure,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,gender,SeniorCitizen,...,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Churn
252,253,9318-NKNFC,One,Month-to-month,Yes,Mailed check,18.85,18.85,Male,0.0,...,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Yes
253,254,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
254,255,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
255,256,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
256,257,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No

In [22]:
df.describe()

       Unnamed: 0  MonthlyCharges  TotalCharges  SeniorCitizen
count  257.000000      247.000000    242.000000     252.000000
mean   129.000000       62.473482   2267.953719       0.134921
std     74.333707       31.126525   2270.876564       0.342319
min      1.000000        3.500000     18.850000       0.000000
25%     65.000000       25.700000    450.687500       0.000000
50%    129.000000       70.300000   1313.025000       0.000000
75%    193.000000       88.325000   3691.187500       0.000000
max    257.000000      115.100000   8337.450000       1.000000

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 257 entries, 0 to 256
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        257 non-null    int64
 1   customerID        257 non-null    object
 2   tenure            257 non-null    object
 3   Contract          257 non-null    object
 4   PaperlessBilling  257 non-null    object
 5   PaymentMethod     257 non-null    object
 6   MonthlyCharges    247 non-null    float64
 7   TotalCharges      242 non-null    float64
 8   gender            257 non-null    object
 9   SeniorCitizen     252 non-null    float64
 10  Partner           257 non-null    object
 11  Dependents        257 non-null    object
 12  PhoneService      257 non-null    object
 13  MultipleLines     257 non-null    object
 14  InternetService   257 non-null    object
 15  OnlineSecurity    257 non-null    object
 16  OnlineBackup      257 non-null    object
 17  DeviceProtection  257 non-null    object
 18  TechSupport       257 non-null    object
 19  StreamingTV       257 non-null    object
 20  StreamingMovies   257 non-null    object
 21  Churn             257 non-null    object
dtypes: float64(3), int64(1), object(18)
memory usage: 44.3+ KB

# Null Values

In [24]:
df.isnull().sum()

Unnamed: 0           0
customerID           0
tenure               0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges      10
TotalCharges        15
gender               0
SeniorCitizen        5
Partner              0
Dependents           0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Churn                0
dtype: int64

Dropping rows with nan values

In [25]:
df.shape

(257, 22)

In [26]:
df_c=df.dropna()
df_c.shape

(227, 22)

In [27]:
df_cax=df.dropna(axis=1)
df_cax.shape

(257, 19)

In [28]:
df.dropna(how='any')

,Unnamed: 0,customerID,tenure,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,gender,SeniorCitizen,...,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Churn
0,1,8260-NGFNY,One,Month-to-month,No,Mailed check,25.20,25.20,Female,0.0,...,No,No phone service,DSL,No,No,No,No,No,No,Yes
1,2,2359-QWQUL,39,One year,Yes,Credit card (automatic),104.70,4134.85,Female,0.0,...,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Yes
2,3,6598/RFFVI,2,One year,No,Credit card (automatic),19.30,28.30,Male,0.0,...,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Yes
3,4,IXSTS-8780,6,Month-to-month,Yes,Electronic check,90.10,521.30,Female,0.0,...,Yes,Yes,Fiber optic,No,Yes,No,No,Yes,No,Yes
4,5,2674/MIAHT,Four,Month-to-month,Yes,Mailed check,80.30,324.20,Female,0.0,...,Yes,Yes,Fiber optic,No,Yes,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,253,9318-NKNFC,One,Month-to-month,Yes,Mailed check,18.85,18.85,Male,0.0,...,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Yes
253,254,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
254,255,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
255,256,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
256,257,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No

In [29]:
df.dropna(inplace=True)

In [30]:
df.shape

(227, 22)

In [31]:
df.isnull().sum()

Unnamed: 0          0
customerID          0
tenure              0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Churn               0
dtype: int64

# Filling the Null values , Replace()

In [32]:
df.fillna(0)

,Unnamed: 0,customerID,tenure,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,gender,SeniorCitizen,...,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Churn
0,1,8260-NGFNY,One,Month-to-month,No,Mailed check,25.20,25.20,Female,0.0,...,No,No phone service,DSL,No,No,No,No,No,No,Yes
1,2,2359-QWQUL,39,One year,Yes,Credit card (automatic),104.70,4134.85,Female,0.0,...,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Yes
2,3,6598/RFFVI,2,One year,No,Credit card (automatic),19.30,28.30,Male,0.0,...,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Yes
3,4,IXSTS-8780,6,Month-to-month,Yes,Electronic check,90.10,521.30,Female,0.0,...,Yes,Yes,Fiber optic,No,Yes,No,No,Yes,No,Yes
4,5,2674/MIAHT,Four,Month-to-month,Yes,Mailed check,80.30,324.20,Female,0.0,...,Yes,Yes,Fiber optic,No,Yes,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,253,9318-NKNFC,One,Month-to-month,Yes,Mailed check,18.85,18.85,Male,0.0,...,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Yes
253,254,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
254,255,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
255,256,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
256,257,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No

In [33]:
df.fillna(method = 'ffill')

C:\Users\Kousimon\AppData\Local\Temp\ipykernel_4240\1145651979.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = 'ffill')

,Unnamed: 0,customerID,tenure,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,gender,SeniorCitizen,...,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Churn
0,1,8260-NGFNY,One,Month-to-month,No,Mailed check,25.20,25.20,Female,0.0,...,No,No phone service,DSL,No,No,No,No,No,No,Yes
1,2,2359-QWQUL,39,One year,Yes,Credit card (automatic),104.70,4134.85,Female,0.0,...,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Yes
2,3,6598/RFFVI,2,One year,No,Credit card (automatic),19.30,28.30,Male,0.0,...,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Yes
3,4,IXSTS-8780,6,Month-to-month,Yes,Electronic check,90.10,521.30,Female,0.0,...,Yes,Yes,Fiber optic,No,Yes,No,No,Yes,No,Yes
4,5,2674/MIAHT,Four,Month-to-month,Yes,Mailed check,80.30,324.20,Female,0.0,...,Yes,Yes,Fiber optic,No,Yes,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,253,9318-NKNFC,One,Month-to-month,Yes,Mailed check,18.85,18.85,Male,0.0,...,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Yes
253,254,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
254,255,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
255,256,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
256,257,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No

In [34]:
df['MonthlyCharges'].fillna(df['MonthlyCharges'].mean())

0       25.20
1      104.70
2       19.30
3       90.10
4       80.30
        ...
252     18.85
253     20.60
254     20.60
255     20.60
256     20.60
Name: MonthlyCharges, Length: 227, dtype: float64

In [35]:
df.fillna(method = 'bfill')

C:\Users\Kousimon\AppData\Local\Temp\ipykernel_4240\3673297803.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = 'bfill')

,Unnamed: 0,customerID,tenure,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,gender,SeniorCitizen,...,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Churn
0,1,8260-NGFNY,One,Month-to-month,No,Mailed check,25.20,25.20,Female,0.0,...,No,No phone service,DSL,No,No,No,No,No,No,Yes
1,2,2359-QWQUL,39,One year,Yes,Credit card (automatic),104.70,4134.85,Female,0.0,...,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Yes
2,3,6598/RFFVI,2,One year,No,Credit card (automatic),19.30,28.30,Male,0.0,...,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Yes
3,4,IXSTS-8780,6,Month-to-month,Yes,Electronic check,90.10,521.30,Female,0.0,...,Yes,Yes,Fiber optic,No,Yes,No,No,Yes,No,Yes
4,5,2674/MIAHT,Four,Month-to-month,Yes,Mailed check,80.30,324.20,Female,0.0,...,Yes,Yes,Fiber optic,No,Yes,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,253,9318-NKNFC,One,Month-to-month,Yes,Mailed check,18.85,18.85,Male,0.0,...,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Yes
253,254,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
254,255,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
255,256,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
256,257,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No

In [36]:
df.replace(to_replace=18 , value=20)

,Unnamed: 0,customerID,tenure,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,gender,SeniorCitizen,...,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Churn
0,1,8260-NGFNY,One,Month-to-month,No,Mailed check,25.20,25.20,Female,0.0,...,No,No phone service,DSL,No,No,No,No,No,No,Yes
1,2,2359-QWQUL,39,One year,Yes,Credit card (automatic),104.70,4134.85,Female,0.0,...,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Yes
2,3,6598/RFFVI,2,One year,No,Credit card (automatic),19.30,28.30,Male,0.0,...,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Yes
3,4,IXSTS-8780,6,Month-to-month,Yes,Electronic check,90.10,521.30,Female,0.0,...,Yes,Yes,Fiber optic,No,Yes,No,No,Yes,No,Yes
4,5,2674/MIAHT,Four,Month-to-month,Yes,Mailed check,80.30,324.20,Female,0.0,...,Yes,Yes,Fiber optic,No,Yes,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,253,9318-NKNFC,One,Month-to-month,Yes,Mailed check,18.85,18.85,Male,0.0,...,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Yes
253,254,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
254,255,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
255,256,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
256,257,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No

In [37]:
df.replace(34,1000)

,Unnamed: 0,customerID,tenure,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,gender,SeniorCitizen,...,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Churn
0,1,8260-NGFNY,One,Month-to-month,No,Mailed check,25.20,25.20,Female,0.0,...,No,No phone service,DSL,No,No,No,No,No,No,Yes
1,2,2359-QWQUL,39,One year,Yes,Credit card (automatic),104.70,4134.85,Female,0.0,...,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Yes
2,3,6598/RFFVI,2,One year,No,Credit card (automatic),19.30,28.30,Male,0.0,...,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Yes
3,4,IXSTS-8780,6,Month-to-month,Yes,Electronic check,90.10,521.30,Female,0.0,...,Yes,Yes,Fiber optic,No,Yes,No,No,Yes,No,Yes
4,5,2674/MIAHT,Four,Month-to-month,Yes,Mailed check,80.30,324.20,Female,0.0,...,Yes,Yes,Fiber optic,No,Yes,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,253,9318-NKNFC,One,Month-to-month,Yes,Mailed check,18.85,18.85,Male,0.0,...,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Yes
253,254,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
254,255,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
255,256,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
256,257,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No

In [38]:
df.replace(to_replace= [18,34], value=[20,1000])

,Unnamed: 0,customerID,tenure,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,gender,SeniorCitizen,...,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Churn
0,1,8260-NGFNY,One,Month-to-month,No,Mailed check,25.20,25.20,Female,0.0,...,No,No phone service,DSL,No,No,No,No,No,No,Yes
1,2,2359-QWQUL,39,One year,Yes,Credit card (automatic),104.70,4134.85,Female,0.0,...,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Yes
2,3,6598/RFFVI,2,One year,No,Credit card (automatic),19.30,28.30,Male,0.0,...,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Yes
3,4,IXSTS-8780,6,Month-to-month,Yes,Electronic check,90.10,521.30,Female,0.0,...,Yes,Yes,Fiber optic,No,Yes,No,No,Yes,No,Yes
4,5,2674/MIAHT,Four,Month-to-month,Yes,Mailed check,80.30,324.20,Female,0.0,...,Yes,Yes,Fiber optic,No,Yes,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,253,9318-NKNFC,One,Month-to-month,Yes,Mailed check,18.85,18.85,Male,0.0,...,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Yes
253,254,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
254,255,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
255,256,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
256,257,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No

In [39]:
df['tenure'].replace(to_replace= ['One','Four'],value = [1,4])
df

,Unnamed: 0,customerID,tenure,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,gender,SeniorCitizen,...,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Churn
0,1,8260-NGFNY,One,Month-to-month,No,Mailed check,25.20,25.20,Female,0.0,...,No,No phone service,DSL,No,No,No,No,No,No,Yes
1,2,2359-QWQUL,39,One year,Yes,Credit card (automatic),104.70,4134.85,Female,0.0,...,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Yes
2,3,6598/RFFVI,2,One year,No,Credit card (automatic),19.30,28.30,Male,0.0,...,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Yes
3,4,IXSTS-8780,6,Month-to-month,Yes,Electronic check,90.10,521.30,Female,0.0,...,Yes,Yes,Fiber optic,No,Yes,No,No,Yes,No,Yes
4,5,2674/MIAHT,Four,Month-to-month,Yes,Mailed check,80.30,324.20,Female,0.0,...,Yes,Yes,Fiber optic,No,Yes,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,253,9318-NKNFC,One,Month-to-month,Yes,Mailed check,18.85,18.85,Male,0.0,...,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Yes
253,254,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
254,255,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
255,256,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
256,257,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No

In [40]:
df.replace('[a-zA-Z]', 0, regex=True)

C:\Users\Kousimon\AppData\Local\Temp\ipykernel_4240\2633244873.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace('[a-zA-Z]', 0, regex=True)

,Unnamed: 0,customerID,tenure,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,gender,SeniorCitizen,...,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Churn
0,1,0,0,0,0,0,25.20,25.20,0,0.0,...,0,0,0,0,0,0,0,0,0,0
1,2,0,39,0,0,0,104.70,4134.85,0,0.0,...,0,0,0,0,0,0,0,0,0,0
2,3,0,2,0,0,0,19.30,28.30,0,0.0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,6,0,0,0,90.10,521.30,0,0.0,...,0,0,0,0,0,0,0,0,0,0
4,5,0,0,0,0,0,80.30,324.20,0,0.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,253,0,0,0,0,0,18.85,18.85,0,0.0,...,0,0,0,0,0,0,0,0,0,0
253,254,0,44,0,0,0,20.60,926.00,0,0.0,...,0,0,0,0,0,0,0,0,0,0
254,255,0,44,0,0,0,20.60,926.00,0,0.0,...,0,0,0,0,0,0,0,0,0,0
255,256,0,44,0,0,0,20.60,926.00,0,0.0,...,0,0,0,0,0,0,0,0,0,0
256,257,0,44,0,0,0,20.60,926.00,0,0.0,...,0,0,0,0,0,0,0,0,0,0

# Loc and Iloc

In [41]:
df

,Unnamed: 0,customerID,tenure,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,gender,SeniorCitizen,...,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Churn
0,1,8260-NGFNY,One,Month-to-month,No,Mailed check,25.20,25.20,Female,0.0,...,No,No phone service,DSL,No,No,No,No,No,No,Yes
1,2,2359-QWQUL,39,One year,Yes,Credit card (automatic),104.70,4134.85,Female,0.0,...,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Yes
2,3,6598/RFFVI,2,One year,No,Credit card (automatic),19.30,28.30,Male,0.0,...,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Yes
3,4,IXSTS-8780,6,Month-to-month,Yes,Electronic check,90.10,521.30,Female,0.0,...,Yes,Yes,Fiber optic,No,Yes,No,No,Yes,No,Yes
4,5,2674/MIAHT,Four,Month-to-month,Yes,Mailed check,80.30,324.20,Female,0.0,...,Yes,Yes,Fiber optic,No,Yes,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,253,9318-NKNFC,One,Month-to-month,Yes,Mailed check,18.85,18.85,Male,0.0,...,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Yes
253,254,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
254,255,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
255,256,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
256,257,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No

In [42]:
df.loc[1]

Unnamed: 0                                2
customerID                       2359-QWQUL
tenure                                   39
Contract                           One year
PaperlessBilling                        Yes
PaymentMethod       Credit card (automatic)
MonthlyCharges                        104.7
TotalCharges                        4134.85
gender                               Female
SeniorCitizen                           0.0
Partner                                 Yes
Dependents                               No
PhoneService                            Yes
MultipleLines                            No
InternetService                 Fiber optic
OnlineSecurity                          Yes
OnlineBackup                             No
DeviceProtection                        Yes
TechSupport                             Yes
StreamingTV                             Yes
StreamingMovies                         Yes
Churn                                   Yes
Name: 1, dtype: object

In [43]:
df.loc[5]

Unnamed: 0                         6
customerID                6077-BDPXA
tenure                             3
Contract              Month-to-month
PaperlessBilling                 Yes
PaymentMethod       Electronic check
MonthlyCharges                 70.15
TotalCharges                   194.2
gender                        Female
SeniorCitizen                    0.0
Partner                           No
Dependents                        No
PhoneService                     Yes
MultipleLines                     No
InternetService          Fiber optic
OnlineSecurity                    No
OnlineBackup                      No
DeviceProtection                  No
TechSupport                       No
StreamingTV                       No
StreamingMovies                   No
Churn                             No
Name: 5, dtype: object

In [44]:
df.loc[[5,6,7,8]]

,Unnamed: 0,customerID,tenure,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,gender,SeniorCitizen,...,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Churn
5,6,6077-BDPXA,3,Month-to-month,Yes,Electronic check,70.15,194.20,Female,0.0,...,Yes,No,Fiber optic,No,No,No,No,No,No,No
6,7,7929/SKFGK,70,Two year,No,Credit card (automatic),114.30,8244.30,Male,0.0,...,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes,No
7,8,7547-EKNFS,42,Month-to-month,Yes,Bank transfer (automatic),95.25,3959.35,Male,0.0,...,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,No,Yes
8,9,5854-KSRBJ,70,Two year,No,Mailed check,25.40,1782.05,Male,0.0,...,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,No

In [45]:
df.loc[1:5,'customerID']

1    2359-QWQUL
2    6598/RFFVI
3    IXSTS-8780
4    2674/MIAHT
5    6077-BDPXA
Name: customerID, dtype: object

In [46]:
df.loc[df['gender']=='Male',['PhoneService']]

    PhoneService
2            Yes
6            Yes
7            Yes
8            Yes
9            Yes
..           ...
252          Yes
253          Yes
254          Yes
255          Yes
256          Yes

[119 rows x 1 columns]

In [47]:
# Iloc

In [48]:
df.iloc[0]

Unnamed: 0                         1
customerID                8260-NGFNY
tenure                           One
Contract              Month-to-month
PaperlessBilling                  No
PaymentMethod           Mailed check
MonthlyCharges                  25.2
TotalCharges                    25.2
gender                        Female
SeniorCitizen                    0.0
Partner                           No
Dependents                        No
PhoneService                      No
MultipleLines       No phone service
InternetService                  DSL
OnlineSecurity                    No
OnlineBackup                      No
DeviceProtection                  No
TechSupport                       No
StreamingTV                       No
StreamingMovies                   No
Churn                            Yes
Name: 0, dtype: object

In [49]:
df.iloc[[0]]

,Unnamed: 0,customerID,tenure,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,gender,SeniorCitizen,...,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Churn
0,1,8260-NGFNY,One,Month-to-month,No,Mailed check,25.2,25.2,Female,0.0,...,No,No phone service,DSL,No,No,No,No,No,No,Yes

In [50]:
df.iloc[0:,4]

0       No
1      Yes
2       No
3      Yes
4      Yes
      ...
252    Yes
253     No
254     No
255     No
256     No
Name: PaperlessBilling, Length: 227, dtype: object

In [51]:
df.iloc[1:5,5]

1    Credit card (automatic)
2    Credit card (automatic)
3           Electronic check
4               Mailed check
Name: PaymentMethod, dtype: object

In [10]:
df

,Unnamed: 0,customerID,tenure,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,gender,SeniorCitizen,...,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Churn
0,1,8260-NGFNY,One,Month-to-month,No,Mailed check,25.20,25.20,Female,0.0,...,No,No phone service,DSL,No,No,No,No,No,No,Yes
1,2,2359-QWQUL,39,One year,Yes,Credit card (automatic),104.70,4134.85,Female,0.0,...,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Yes
2,3,6598/RFFVI,2,One year,No,Credit card (automatic),19.30,28.30,Male,0.0,...,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Yes
3,4,IXSTS-8780,6,Month-to-month,Yes,Electronic check,90.10,521.30,Female,0.0,...,Yes,Yes,Fiber optic,No,Yes,No,No,Yes,No,Yes
4,5,2674/MIAHT,Four,Month-to-month,Yes,Mailed check,80.30,324.20,Female,0.0,...,Yes,Yes,Fiber optic,No,Yes,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,253,9318-NKNFC,One,Month-to-month,Yes,Mailed check,18.85,18.85,Male,0.0,...,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Yes
253,254,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
254,255,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
255,256,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No
256,257,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.60,926.00,Male,0.0,...,Yes,No,No,Yes,Yes,No internet service,No internet service,Yes,No internet service,No

AT[],IAT[]

In [9]:
df.at[1,'tenure']

'39'

In [11]:
df.iat[2,3]

'One year'

# GroupBy

In [55]:
df.nunique()

Unnamed: 0          227
customerID          220
tenure               67
Contract              3
PaperlessBilling      2
PaymentMethod         4
MonthlyCharges      200
TotalCharges        219
gender                2
SeniorCitizen         2
Partner               2
Dependents            3
PhoneService          2
MultipleLines         3
InternetService       3
OnlineSecurity        3
OnlineBackup          3
DeviceProtection      3
TechSupport           3
StreamingTV           3
StreamingMovies       3
Churn                 2
dtype: int64

In [54]:
branch_group= df.groupby(by='PaymentMethod')
branch_group

In [57]:
df.groupby(by=['PaymentMethod','gender'])
branch_group.groups

{'Bank transfer (automatic)': [7, 16, 17, 30, 40, 45, 46, 47, 48, 55, 56, 57, 59, 60, 64, 66, 70, 76, 84, 86, 89, 90, 94, 114, 124, 129, 142, 143, 155, 157, 163, 164, 167, 171, 173, 183, 185, 189, 199, 200, 204, 206, 209, 210, 212, 215, 219, 222, 223, 224, 230, 231, 246, 248, 253, 254, 255, 256], 'Credit card (automatic)': [1, 2, 6, 18, 20, 23, 25, 26, 27, 37, 43, 50, 51, 58, 63, 75, 80, 81, 83, 85, 87, 88, 95, 109, 115, 122, 125, 127, 131, 136, 140, 141, 146, 148, 154, 156, 159, 160, 165, 168, 169, 180, 181, 193, 205, 211, 226, 227, 238, 240, 243, 245], 'Electronic check': [3, 5, 9, 12, 15, 19, 21, 22, 28, 29, 33, 35, 38, 44, 49, 52, 54, 61, 62, 65, 68, 73, 82, 93, 96, 98, 100, 101, 102, 105, 106, 108, 110, 116, 117, 120, 137, 149, 153, 158, 174, 175, 177, 178, 179, 186, 187, 188, 190, 195, 197, 202, 203, 207, 214, 216, 217, 220, 228, 229, 233, 234, 239, 241, 244, 247, 251], 'Mailed check': [0, 4, 8, 10, 11, 14, 24, 31, 32, 34, 36, 39, 72, 74, 77, 78, 99, 103, 107, 111, 112, 113, 119, 123, 126, 128, 130, 132, 144, 145, 147, 150, 151, 161, 162, 166, 191, 192, 196, 198, 208, 218, 225, 232, 235, 236, 237, 242, 249, 252]}

In [59]:
for group, data_frame in branch_group:
    print(group)
    print(data_frame)

Bank transfer (automatic)
     Unnamed: 0  customerID tenure        Contract PaperlessBilling  \
7             8  7547-EKNFS     42  Month-to-month              Yes
16           17  2612-PHGOX     64        Two year              Yes
17           18  6874-SGLHU     30        One year              Yes
30           31  6463-HHXJR     71        Two year               No
40           41  8853-TZDGH     72        Two year              Yes
45           46  9067-SQTNS     44        One year               No
46           47  9067-SQTNS     44        One year               No
47           48  9067-SQTNS     44        One year               No
48           49  9067-SQTNS     44        One year               No
55           56  9823-EALYC     72        Two year              Yes
56           57  1591-MQJTP     51        One year              Yes
57           58  4480-QQRHC      8  Month-to-month              Yes
59           60  3585-YNADK     57        One year               No
60           61  3733-UOCWF     61        One year              Yes
64           65  0495-ZBNGW      5  Month-to-month              Yes
66           67  0402-CQAJN     37  Month-to-month              Yes
70           71  2040-XBAVJ     72        Two year               No
76           77  3889-VWBID     68        Two year               No
84           85  0431-APWVY     28        One year              Yes
86           87  8869-LIHMK     64        Two year              Yes
89           90  1754-GKYPY     22  Month-to-month              Yes
90           91  8404-VIOMB     66        Two year              Yes
94           95  4818-DRBQT     29  Month-to-month              Yes
114         115  3842-QTGDL     16  Month-to-month               No
124         125  1096-ADRUX     66        One year              Yes
129         130  1094-BKOSX     45        One year               No
142         143  0607-DAAHE     53        Two year               No
143         144  2458-EOMRE     11  Month-to-month               No
155         156  1485-YDHMM     52  Month-to-month              Yes
157         158  6142-VSJQO    One  Month-to-month              Yes
163         164  5419-KLXBN     25  Month-to-month              Yes
164         165  3703-KBKZP     16  Month-to-month              Yes
167         168  3452-FLHYD     25        One year              Yes
171         172  9961-JBNMK     21  Month-to-month              Yes
173         174  7009-LGECI   Four  Month-to-month              Yes
183         184  0203-HHYIJ     25        One year               No
185         186  9746-UGFAC     22        One year               No
189         190  7856-GANIL     45        One year              Yes
199         200  9812-GHVRI     40  Month-to-month               No
200         201  2676-SSLTO     49        Two year              Yes
204         205  4070-OKWVH     52  Month-to-month               No
206         207  5708-EVONK     58  Month-to-month              Yes
209         210  0913-XWSCN     55  Month-to-month               No
210         211  3649-JPUGY     72        Two year              Yes
212         213  3090-LETTY      2  Month-to-month               No
215         216  4291-TPNFG     72        Two year              Yes
219         220  7730-CLDSV     72        Two year              Yes
222         223  7673-BQGKU     69        Two year               No
223         224  3128-YOVTD    969  Month-to-month              Yes
224         225  5304-EFJLP     72        Two year              Yes
230         231  4130-MZLCC      5  Month-to-month               No
231         232  4686-GEFRM     70        Two year              Yes
246         247  2589-AYCRP     50        One year               No
248         249  8111-RKSPX   Four  Month-to-month              Yes
253         254  9067-SQTNS     44        One year               No
254         255  9067-SQTNS     44        One year               No
255         256  9067-SQTNS     44        One year               No
256         257  9067-SQTNS     44        One year               No

                 PaymentMethod  MonthlyCharges  TotalCharges  gender  \
7    Bank transfer (automatic)           95.25       3959.35    Male
16   Bank transfer (automatic)           76.10       4818.80    Male
17   Bank transfer (automatic)           97.00       3021.30    Male
30   Bank transfer (automatic)          100.50       7030.65  Female
40   Bank transfer (automatic)          111.60       8012.75  Female
45   Bank transfer (automatic)           20.60        926.00    Male
46   Bank transfer (automatic)           20.60        926.00    Male
47   Bank transfer (automatic)           20.60        926.00    Male
48   Bank transfer (automatic)           20.60        926.00    Male
55   Bank transfer (automatic)            3.50       5727.45    Male
56   Bank transfer (automatic)           93.65       4839.15    Male
57   Bank transfer (automatic)           74.05        600.15  Female
59   Bank transfer (automatic)           74.60       4368.95  Female
60   Bank transfer (automatic)           85.55       5251.75    Male
64   Bank transfer (automatic)           79.90        343.95    Male
66   Bank transfer (automatic)          101.90       3545.35  Female
70   Bank transfer (automatic)          114.45       8100.55    Male
76   Bank transfer (automatic)           82.85       5776.45    Male
84   Bank transfer (automatic)            8.00       2598.95  Female
86   Bank transfer (automatic)          115.10       7334.05  Female
89   Bank transfer (automatic)           89.75       1938.90    Male
90   Bank transfer (automatic)           62.50       4136.40  Female
94   Bank transfer (automatic)           80.15       2265.25    Male
114  Bank transfer (automatic)           80.75       1321.30    Male
124  Bank transfer (automatic)           74.25       4859.25  Female
129  Bank transfer (automatic)           51.00       2264.50  Female
142  Bank transfer (automatic)           19.75       1052.35    Male
143  Bank transfer (automatic)           64.05        733.95  Female
155  Bank transfer (automatic)           93.25       4631.70    Male
157  Bank transfer (automatic)           44.35         44.35  Female
163  Bank transfer (automatic)           89.15       2257.75  Female
164  Bank transfer (automatic)           74.45       1261.35    Male
167  Bank transfer (automatic)           20.95        495.15    Male
171  Bank transfer (automatic)           96.80       2030.30    Male
173  Bank transfer (automatic)           50.55        235.65  Female
183  Bank transfer (automatic)           25.30        676.35    Male
185  Bank transfer (automatic)           20.85        450.65  Female
189  Bank transfer (automatic)           98.70       4525.80    Male
199  Bank transfer (automatic)           83.85       3532.25  Female
200  Bank transfer (automatic)           66.15       3199.00    Male
204  Bank transfer (automatic)           94.60       5025.80  Female
206  Bank transfer (automatic)           93.40       5435.60  Female
209  Bank transfer (automatic)           85.50       4713.40    Male
210  Bank transfer (automatic)           88.60       6201.95    Male
212  Bank transfer (automatic)           60.95        134.60    Male
215  Bank transfer (automatic)           82.30       5980.55    Male
219  Bank transfer (automatic)           98.65       7129.45  Female
222  Bank transfer (automatic)           20.15       1337.50  Female
223  Bank transfer (automatic)           79.15       4018.55  Female
224  Bank transfer (automatic)          111.65       8022.85    Male
230  Bank transfer (automatic)           50.55        244.75  Female
231  Bank transfer (automatic)           98.70       6858.90    Male
246  Bank transfer (automatic)           19.75        989.05  Female
248  Bank transfer (automatic)           72.20        305.55    Male
253  Bank transfer (automatic)           20.60        926.00    Male
254  Bank transfer (automatic)           20.60        926.00    Male
255  Bank transfer (automatic)           20.60        926.00    Male
256  Bank transfer (automatic)           20.60        926.00    Male

     SeniorCitizen  ... PhoneService     MultipleLines InternetService  \
7              0.0  ...          Yes               Yes     Fiber optic
16             0.0  ...          Yes               Yes             DSL
17             0.0  ...          Yes                No     Fiber optic
30             0.0  ...          Yes               Yes     Fiber optic
40             0.0  ...          Yes               Yes     Fiber optic
45             0.0  ...          Yes                No              No
46             0.0  ...          Yes                No              No
47             0.0  ...          Yes                No              No
48             0.0  ...          Yes                No              No
55             0.0  ...          Yes               Yes             DSL
56             1.0  ...          Yes               Yes     Fiber optic
57             1.0  ...          Yes                No     Fiber optic
59             0.0  ...          Yes               Yes             DSL
60             1.0  ...          Yes               Yes     Fiber optic
64             1.0  ...          Yes               Yes     Fiber optic
66             0.0  ...          Yes               Yes     Fiber optic
70             0.0  ...          Yes               Yes     Fiber optic
76             0.0  ...          Yes                No             DSL
84             0.0  ...          Yes                No     Fiber optic
86             0.0  ...          Yes               Yes     Fiber optic
89             1.0  ...          Yes                No     Fiber optic
90             0.0  ...           No  No phone service             DSL
94             0.0  ...          Yes               Yes     Fiber optic
114            0.0  ...          Yes                No     Fiber optic
124            0.0  ...          Yes               Yes     Fiber optic
129            0.0  ...           No  No phone service             DSL
142            0.0  ...          Yes                No              No
143            0.0  ...          Yes                No             DSL
155            0.0  ...          Yes               Yes     Fiber optic
157            0.0  ...          Yes                No             DSL
163            0.0  ...          Yes                No     Fiber optic
164            1.0  ...          Yes               Yes     Fiber optic
167            0.0  ...          Yes                No              No
171            1.0  ...          Yes                No     Fiber optic
173            0.0  ...          Yes                No             DSL
183            0.0  ...          Yes               Yes              No
185            0.0  ...          Yes                No              No
189            1.0  ...          Yes               Yes     Fiber optic
199            0.0  ...          Yes               Yes     Fiber optic
200            0.0  ...          Yes               Yes             DSL
204            0.0  ...          Yes               Yes     Fiber optic
206            0.0  ...          Yes               Yes     Fiber optic
209            0.0  ...          Yes               Yes     Fiber optic
210            0.0  ...          Yes               Yes             DSL
212            0.0  ...          Yes               Yes             DSL
215            0.0  ...          Yes               Yes             DSL
219            0.0  ...          Yes               Yes     Fiber optic
222            0.0  ...          Yes                No              No
223            0.0  ...          Yes                No     Fiber optic
224            1.0  ...          Yes               Yes     Fiber optic
230            0.0  ...          Yes                No             DSL
231            0.0  ...          Yes               Yes     Fiber optic
246            0.0  ...          Yes                No              No
248            0.0  ...          Yes               Yes     Fiber optic
253            0.0  ...          Yes                No              No
254            0.0  ...          Yes                No              No
255            0.0  ...          Yes                No              No
256            0.0  ...          Yes                No              No

          OnlineSecurity         OnlineBackup     DeviceProtection  \
7                     No                  Yes                  Yes
16                    No                  Yes                  Yes
17                    No                  Yes                   No
30                   Yes                  Yes                  Yes
40                    No                  Yes                  Yes
45                   Yes                  Yes  No internet service
46                   Yes                  Yes  No internet service
47                   Yes                  Yes  No internet service
48                   Yes                  Yes  No internet service
55                   Yes                  Yes                  Yes
56                   Yes                   No                  Yes
57                    No                   No                  Yes
59                    No                  Yes                  Yes
60                    No                  Yes                   No
64                    No                   No                  Yes
66                    No                  Yes                  Yes
70                   Yes                  Yes                  Yes
76                   Yes                  Yes                   No
84                    No                   No                   No
86                   Yes                  Yes                  Yes
89                    No                   No                   No
90                   Yes                  Yes                  Yes
94                    No                  Yes                   No
114                  Yes                  Yes                   No
124                   No                   No                   No
129                   No                  Yes                  Yes
142  No internet service  No internet service  No internet service
143                  Yes                   No                  Yes
155                   No                  Yes                   No
157                   No                   No                   No
163                   No                  Yes                  Yes
164                   No                   No                   No
167  No internet service  No internet service  No internet service
171                   No                   No                  Yes
173                  Yes                   No                   No
183  No internet service  No internet service  No internet service
185  No internet service  No internet service  No internet service
189                   No                  Yes                  Yes
199                   No                   No                   No
200                   No                   No                   No
204                   No                  Yes                  Yes
206                  Yes                  Yes                   No
209                   No                   No                   No
210                   No                  Yes                  Yes
212                  Yes                  Yes                   No
215                  Yes                  Yes                  Yes
219                   No                  Yes                  Yes
222  No internet service  No internet service  No internet service
223                  Yes                  Yes                   No
224                   No                  Yes                  Yes
230                   No                  Yes                   No
231                   No                  Yes                  Yes
246  No internet service  No internet service  No internet service
248                   No                   No                   No
253                  Yes                  Yes  No internet service
254                  Yes                  Yes  No internet service
255                  Yes                  Yes  No internet service
256                  Yes                  Yes  No internet service

             TechSupport          StreamingTV      StreamingMovies Churn
7                     No                  Yes                   No   Yes
16                   Yes  No internet service  No internet service    No
17                    No                  Yes                  Yes    No
30                    No                  Yes                   No    No
40                   Yes                  Yes                  Yes    No
45   No internet service                  Yes  No internet service    No
46   No internet service                  Yes  No internet service    No
47   No internet service                  Yes  No internet service    No
48   No internet service                  Yes  No internet service    No
55                   Yes                  Yes                   No    No
56                    No                   No                  Yes    No
57                    No                   No                   No    No
59                   Yes                  Yes                   No    No
60                   Yes                   No                   No    No
64                    No                   No                   No   Yes
66                    No                  Yes                  Yes   Yes
70                   Yes                  Yes                  Yes    No
76                   Yes                  Yes                  Yes    No
84                    No                  Yes                  Yes   Yes
86                   Yes                  Yes                  Yes    No
89                    No                  Yes                  Yes    No
90                   Yes                  Yes                  Yes    No
94                    No                   No                   No   Yes
114                   No                   No                   No    No
124                   No                   No                   No    No
129                  Yes                   No                  Yes    No
142  No internet service  No internet service  No internet service   Yes
143                   No                   No                  Yes    No
155                  Yes                   No                  Yes    No
157                   No                   No                   No   Yes
163                   No                  Yes                   No   Yes
164                   No                   No                   No    No
167  No internet service  No internet service  No internet service    No
171                   No                  Yes                  Yes   Yes
173                   No                   No                   No    No
183  No internet service  No internet service  No internet service   Yes
185  No internet service  No internet service  No internet service    No
189                  Yes                  Yes                   No    No
199                   No                   No                  Yes    No
200                  Yes                  Yes                   No    No
204                   No                  Yes                   No    No
206                   No                   No                  Yes   Yes
209                   No                   No                  Yes    No
210                  Yes                  Yes                  Yes    No
212                   No                   No                   No    No
215                  Yes                   No                  Yes    No
219                  Yes                   No                  Yes    No
222  No internet service  No internet service  No internet service    No
223                   No                   No                   No    No
224                  Yes                  Yes                  Yes    No

# Merge

In [64]:
df1=pd.DataFrame({'Roll_no':[1,2,3,4,5],'Physics':[6,7,8,9,10]})
df1

   Roll_no  Physics
0        1        6
1        2        7
2        3        8
3        4        9
4        5       10

In [67]:
df2=pd.DataFrame({'Roll_no':[1,2,3,4,5],'Chemistry':[11,12,13,14,15]})
df2

   Roll_no  Chemistry
0        1         11
1        2         12
2        3         13
3        4         14
4        5         15

In [68]:
pd.merge(df1,df2,on='Roll_no')

   Roll_no  Chemistry_x  Chemistry_y
0        1           11           11
1        2           12           12
2        3           13           13
3        4           14           14
4        5           15           15

In [69]:
pd.merge(df2,df1,on = 'Roll_no')

   Roll_no  Chemistry_x  Chemistry_y
0        1           11           11
1        2           12           12
2        3           13           13
3        4           14           14
4        5           15           15

In [71]:
df3=pd.DataFrame({'Roll_no:':[12,3,4,5,6],'Physics':[12,87,67,4,3]})
df4=pd.DataFrame({'Roll_no:':[12,3,8,9,6],'Chemistry':[12,87,67,4,3]})

pd.merge(df3,df4)

   Roll_no:  Physics  Chemistry
0        12       12         12
1         3       87         87
2         6        3          3

In [73]:
pd.merge(df3,df4, how = 'left')

   Roll_no:  Physics  Chemistry
0        12       12       12.0
1         3       87       87.0
2         4       67        NaN
3         5        4        NaN
4         6        3        3.0

In [74]:
pd.merge(df3,df4,how = 'right')

   Roll_no:  Physics  Chemistry
0        12     12.0         12
1         3     87.0         87
2         8      NaN         67
3         9      NaN          4
4         6      3.0          3

In [75]:
pd.merge(df3,df4, how = 'outer')

   Roll_no:  Physics  Chemistry
0         3     87.0       87.0
1         4     67.0        NaN
2         5      4.0        NaN
3         6      3.0        3.0
4         8      NaN       67.0
5         9      NaN        4.0
6        12     12.0       12.0

# Append

In [78]:
df1=pd.DataFrame({'Roll_no':[1,2,3,4,5],'Physics':[6,7,8,9,10],'Maths':[45,24,64,77,78]})
df2=pd.DataFrame({'Roll_no':[1,2,3,4,5],'Physics':[11,12,13,14,15],'Maths':[48,74,44,37,88]})

print(df1)
print(df2)

   Roll_no  Physics  Maths
0        1        6     45
1        2        7     24
2        3        8     64
3        4        9     77
4        5       10     78
   Roll_no  Physics  Maths
0        1       11     48
1        2       12     74
2        3       13     44
3        4       14     37
4        5       15     88

In [82]:
df1.append(df2)

AttributeError: 'DataFrame' object has no attribute 'append'

In [83]:
df1.append(df2,ignore_index=True,sort = True)

AttributeError: 'DataFrame' object has no attribute 'append'

# Pivot Table

This is used to find the average values based on one column

In [86]:
df.head()

,Unnamed: 0,customerID,tenure,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,gender,SeniorCitizen,...,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Churn
0,1,8260-NGFNY,One,Month-to-month,No,Mailed check,25.2,25.20,Female,0.0,...,No,No phone service,DSL,No,No,No,No,No,No,Yes
1,2,2359-QWQUL,39,One year,Yes,Credit card (automatic),104.7,4134.85,Female,0.0,...,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Yes
2,3,6598/RFFVI,2,One year,No,Credit card (automatic),19.3,28.30,Male,0.0,...,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Yes
3,4,IXSTS-8780,6,Month-to-month,Yes,Electronic check,90.1,521.30,Female,0.0,...,Yes,Yes,Fiber optic,No,Yes,No,No,Yes,No,Yes
4,5,2674/MIAHT,Four,Month-to-month,Yes,Mailed check,80.3,324.20,Female,0.0,...,Yes,Yes,Fiber optic,No,Yes,No,No,No,No,No

In [90]:
pd.pivot_table(df3,index='MonthlyCharges')

KeyError: 'MonthlyCharges'

In [92]:
pd.pivot_table(df,index= 'PaymentMethod',aggfunc='sum',columns='Contract')

                                                                       Churn  \
Contract                                                      Month-to-month
PaymentMethod
Bank transfer (automatic)  YesNoYesYesNoYesNoNoNoYesYesNoYesNoNoNoYesNoNo...
Credit card (automatic)                               YesNoYesYesYesNoYesYes
Electronic check           YesNoYesNoYesYesNoNoYesYesYesYesYesYesYesNoNoY...
Mailed check               YesNoYesNoNoNoNoYesNoNoNoNoNoYesNoYesYesNoNoYe...

                                                                            \
Contract                                                          One year
PaymentMethod
Bank transfer (automatic)       NoNoNoNoNoNoNoNoYesNoNoNoYesNoNoNoNoNoNoNo
Credit card (automatic)    YesYesNoNoYesNoNoNoNoNoNoNoNoNoNoYesYesNoNoNoNo
Electronic check                                   YesNoNoNoNoNoNoNoYesYes
Mailed check                                             NoNoNoNoNoYesNoNo

                                                                           \
Contract                                                         Two year
PaymentMethod
Bank transfer (automatic)               NoNoNoNoNoNoNoNoYesNoNoNoNoNoNoNo
Credit card (automatic)    NoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNo
Electronic check                                                   NoNoNo
Mailed check                                       NoNoNoNoNoNoNoNoNoNoNo

                                                                  Dependents  \
Contract                                                      Month-to-month
PaymentMethod
Bank transfer (automatic)  NoNoNoNo1@#NoNoNoYesYesYesNoNoNoNoNoYesYesYesY...
Credit card (automatic)                                 YesYesYesNoNoNoYesNo
Electronic check           NoNoYesYesNoNoYesNoYesNoNoYesNoNoNoYesYesNoNoN...
Mailed check               NoNoNoYesNoNoNoNoNoNoYesNoNoNoYesYesNoNoNoNoNo...

                                                                              \
Contract                                                            One year
PaymentMethod
Bank transfer (automatic)  NoYesYesYesYesNoNoNoYesYesYesNoNoNoNoNoYesYesY...
Credit card (automatic)     NoNoNoYesYesNoNoNoNoNoYesNoNoYesNoNoNoNoYesNoYes
Electronic check                                    YesNoNoYesNoYesYesNoNoNo
Mailed check                                             NoNoNoNoYesNoYesYes

                                                                              \
Contract                                                            Two year
PaymentMethod
Bank transfer (automatic)            NoYesNoYesYesYesNoNoYesNoNoNoYesYesNoNo
Credit card (automatic)    NoNoYesNoYesNoNoYesNoNoNo1@#NoYesNoYesYesNoYes...
Electronic check                                                     NoYesNo
Mailed check                                      YesNoYesNoYesNoNoNoNoNoYes

                                                            DeviceProtection  \
Contract                                                      Month-to-month
PaymentMethod
Bank transfer (automatic)  YesYesYesYesNoNoNoYesNoNoYesNoYesNoNoYesNoNoNo...
Credit card (automatic)                                 NoNoYesYesNoNoYesYes
Electronic check           NoNoNoNo internet serviceNoNoNoYesYesYesNoNoNo...
Mailed check               NoNoNoNo internet serviceNo internet serviceYe...

                                                                              \
Contract                                                            One year
PaymentMethod
Bank transfer (automatic)  NoNo internet serviceNo internet serviceNo int...
Credit card (automatic)    YesNo internet serviceNoYesYesYesYesYesYesNoYe...
Electronic check                                 NoYesNoYesYesYesNoYesYesYes
Mailed check               NoNo internet serviceYesNo internet serviceNo ...

                                                                              \
Contract                                                            Two year
PaymentMethod
Bank transfer (automatic)  YesYesYesYesYesNoYesYesNo internet serviceNoYe...
Credit card (automatic)    YesNo internet serviceNo internet serviceNo in...
Electronic check                                                   YesYesYes
Mailed check               No internet serviceYesNo internet serviceYesNo...

                                                             InternetService  \
Contract                                                      Month-to-month
PaymentMethod
Bank transfer (automatic)  Fiber opticFiber opticFiber opticFiber opticFi...
Credit card (automatic)     DSLDSLDSLFiber opticDSLDSLFiber opticFiber optic
Electronic check           Fiber opticFiber opticFiber opticNoFiber optic...
Mailed check               DSLFiber opticFiber opticNoNoDSLFiber opticFib...

                           ... Unnamed: 0  \
Contract                   ...   Two year
PaymentMethod              ...
Bank transfer (automatic)  ...       2142
Credit card (automatic)    ...       2775
Electronic check           ...        181
Mailed check               ...       1628

                                                                  customerID  \
Contract                                                      Month-to-month
PaymentMethod
Bank transfer (automatic)  7547-EKNFS4480-QQRHC0495-ZBNGW0402-CQAJN1754-G...
Credit card (automatic)    1114-CENIM3701-SFMUH6207-WIOLX7627-JKIAZ9210-I...
Electronic check           IXSTS-87806077-BDPXA5054-IEXZT9374-YOLBJ6513-E...
Mailed check               8260-NGFNY2674/MIAHT7235-NXZCP9184-GALIL2592-Y...

                                                                              \
Contract                                                            One year
PaymentMethod
Bank transfer (automatic)  6874-SGLHU9067-SQTNS9067-SQTNS9067-SQTNS9067-S...
Credit card (automatic)    2359-QWQUL6598/RFFVI9762-YAQAA1090-PYKCI4106-H...
Electronic check           3325-FUYCG6362-QHAFM1422-DGUBX2272-JKMSI2000-M...
Mailed check               1877-HKBQX0307-BCOPK8898-KASCD9824-QCJPK1561-B...

                                                                              \
Contract                                                            Two year
PaymentMethod
Bank transfer (automatic)  2612-PHGOX6463-HHXJR8853-TZDGH9823-EALYC2040-X...
Credit card (automatic)    7929/SKFGK9588-YRFHY1306-RPWXZ8464-EETCQ3399-B...
Electronic check                              2307-FYNNL7572-KPVKK6504-VBLFL
Mailed check               5854-KSRBJ6374-AFWOX8946-BFWSG2845-KDHVX3620-E...

                                                                      gender  \
Contract                                                      Month-to-month
PaymentMethod
Bank transfer (automatic)  MaleFemaleMaleFemaleMaleMaleMaleFemaleMaleFema...
Credit card (automatic)           MaleMaleFemaleFemaleFemaleMaleFemaleFemale
Electronic check           FemaleFemaleMaleFemaleMaleMaleFemaleFemaleMale...
Mailed check               FemaleFemaleMaleFemaleFemaleMaleMaleMaleMaleMa...

                                                                              \
Contract                                                            One year
PaymentMethod
Bank transfer (automatic)  MaleMaleMaleMaleMaleMaleFemaleMaleFemaleFemale...
Credit card (automatic)    FemaleMaleMaleFemaleMaleFemaleMaleMaleMaleFema...
Electronic check           MaleMaleMaleFemaleFemaleFemaleFemaleFemaleFema...
Mailed check                            FemaleFemaleMaleMaleMaleMaleMaleMale

                                                                              \
Contract                                                            Two year
PaymentMethod
Bank transfer (automatic)  MaleFemaleFemaleMaleMaleMaleFemaleFemaleMaleMa...
Credit card (automatic)    MaleMaleFemaleMaleMaleMaleMaleMaleMaleMaleFema...
Electronic check                                                MaleMaleMale
Mailed check               MaleMaleMaleFemaleFemaleFemaleFemaleFemaleFema...

                                                                      tenure  \
Contract                                                      Month-to-month
PaymentMethod
Bank transfer (automatic)     4285372229161152One251621Four4052585529695Four
Credit card (automatic)                                      549942537710169
Electronic check           63OneOneOneOne102549138971FourOne1068910347132...
Mailed check               OneFour238One1721FourOne32727Four28OneOne99215...

                                                                       \
Contract                                                     One year
PaymentMethod
Bank transfer (automatic)    3044444444515761286645252522455044444444
Credit card (automatic)    392396939446848642243564912701958715596464
Electronic check                                  2842326258728417255
Mailed check                                          111639361955856


Contract                                                         Two year
PaymentMethod
Bank transfer (automatic)                64717272726864665349727272697270
Credit card (automatic)    7049495751631866723762104361647272636272716548
Electronic check                                                   656255
Mailed check                                        704663645265726731569

[4 rows x 60 columns]

In [6]:
from datetime import date,datetime,time,timedelta

In [13]:
dates=timedelta(days=7)
dates
now=datetime.now()
nextweek=now+dates

In [14]:
nextweek

datetime.datetime(2025, 6, 5, 21, 36, 46, 963158)

In [ ]:
noon=